### ISSUE TITLE
打开IP+52764端口网页只显示Upgrade Required

### ISSUE THREAD

**Issue by fff122** [CrosSt-Chat/CSC-main#10]
- 打开后只显示Upgrade Required，
这是日志
` 
 up to date, audited 2 packages in 756ms

 found 0 vulnerabilities
 npm notice 
 npm notice New minor version of npm available! 10.2.4 -> 10.7.0
 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.7.0>
 npm notice Run `npm install -g npm@10.7.0` to update!
 npm notice 
 Initializing CSC-backend...

* Initializing /app/init/core/address-checker.js ...
 * Initializing /app/init/core/app-config.js ...
 * Initializing /app/init/core/handle-error.js ...
 * Initializing /app/init/core/logger.js ...
 * Initializing /app/init/core/rate-limiter.js ...
 * Initializing /app/init/core/stats.js ...
 * Initializing /app/init/utility.js ...
 * Initializing /app/init/ws/can-speak.js ...
 * Initializing /app/init/ws/cscsocket.js ...
 * Initializing /app/init/ws/disconnect.js ...
 * Initializing /app/init/ws/handle-massage.js ...
 * Initializing /app/init/ws/server.js ...
 * Initializing /app/init/ws/verify.js ...
 √ Initialize inits complete!
 * Initializing /app/src/command/admin/ban.js ...
* Initializing /app/src/command/admin/banip.js ...
 * Initializing /app/src/command/admin/broadcast.js ...
 * Initializing /app/src/command/admin/ipcheck.js ...
 * Initializing /app/src/command/admin/lockroom.js ...
 * Initializing /app/src/command/admin/locksite.js ...
 * Initializing /app/src/command/admin/member-add.js ...
 * Initializing /app/src/command/admin/member-remove.js ...
 * Initializing /app/src/command/admin/mute.js ...
 * Initializing /app/src/command/admin/roomlist.js ...
 * Initializing /app/src/command/admin/unban.js ...
 * Initializing /app/src/command/admin/unbanall.js ...
* Initializing /app/src/command/admin/unlockroom.js ...
 * Initializing /app/src/command/admin/unlocksite.js ...
 * Initializing /app/src/command/guest/getinfo.js ...
 * Initializing /app/src/command/guest/join.js ...
 * Initializing /app/src/command/guest/ping.js ...
 * Initializing /app/src/command/member/stats.js ...
 * Initializing /app/src/command/root/admin-add.js ...
* Initializing /app/src/command/root/admin-remove.js ...
 * Initializing /app/src/command/root/elevate.js ...
 * Initializing /app/src/command/root/reload.js ...
 * Initializing /app/src/command/user/chat.js ...
 * Initializing /app/src/command/user/emote.js ...
 * Initializing /app/src/command/user/invite.js ...
 * Initializing /app/src/command/user/kickme.js ...
 * Initializing /app/src/command/user/whisper-r.js ...
 * Initializing /app/src/command/user/whisper-w.js ...
 * Initializing /app/src/command/user/whisper.js ...
 * Initializing /app/src/ws/handle-connection.js ...
 * Initializing /app/src/ws/heartbeat.js ...
 √ Initialize functions complete!

√ Static function executed.
 ==CSC-backend Initialize Complete==
`

node版本为v20.12.2(LTS)
用的1panel面板部署

ubuntu@ip-172-31-4-148:~$ npm -v
10.7.0
ubuntu@ip-172-31-4-148:~$ node -v
v20.12.2

**Comment by iiishop** [comment]
我也碰上了同样问题，请问是如何解决的

**Comment by yj94** [comment]
同问

**Comment by Hex-0xd3ac** [comment]
客户端可在:https://github.com/CrosSt-Chat/CSC-main/tree/1e210044bfd7bfbe6d91f8b4ad1e82cc861ae303找到
